version: '3.8'

services:
  web:
    build: .
    ports:
      - "8005:8000"  # Puerto expuesto en el contenedor
    volumes:
      - ./src:/src   # Montar el directorio src al contenedor
    environment:
      - ENV_VAR=example
